### PR TITLE
Release to Master

### PR DESCRIPTION
**Pull request by erikeggers**
I currently need to work on two more views and complete my footer. Submitting because I have not heard back from @brandonbrown  regarding my extension, so I am not sure what to do.

### CODE REVIEW

**Comment by erikeggers** [comment]
This was ready to go yesterday. I realized I did not leave a comment here.

**Comment by erikeggers** [comment]
I have updated my documentation @brandonbrown @reactivepixel

**Comment by brandonbrown** [comment]
Good work getting these updates in @erikeggers. It looks like everything has been addressed but the multiple packages. @reactivepixel shared information about this. If you're not planning on addressing this, please leave an update here with an explanation why you're not addressing it or why you think it's not appropriate to address within this update.

**Comment by erikeggers** [comment]
I was told that I could continue doing what I was doing with concurrently in the video that @reactivepixel made for me. I plan on changing that out to what @reactivepixel suggested I do so I can expand upon my app later.

**Comment by brandonbrown** [comment]
Okay great. In that case, @reactivepixel should be the one to give final approval for this PR. Thank you for the update!

**Comment by erikeggers** [comment]
Milestone 4 is also part of this pull request: https://github.com/FullSail/capstone-erikeggers/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Sprint+4%22

**Pull request merged**
